### ISSUE TITLE
Barlow Thin and Extra light has Problem with letters bdpq

### ISSUE THREAD

**Issue by xcolomer** [jpt/barlow#100]
Hi 
There is a problem in tipography BarlowSemiCondensed (Thin / ExtraLight) whith b d p q letters

**Incorrect display**
BarlowSemiCondensed-ThinItalic.ttf
![image](https://github.com/jpt/barlow/assets/12183886/30c6e8c3-0236-4c6c-bd8b-c51772e98699)

BarlowSemiCondensed-Thin.ttf
![image](https://github.com/jpt/barlow/assets/12183886/68cc778c-3615-4aad-9b97-52070d38ce98)

BarlowSemiCondensed-ExtraLight.ttf
![image](https://github.com/jpt/barlow/assets/12183886/4b10d4e2-9837-46cb-bea1-36d69378864c)

BarlowSemiCondensed-ExtraLightItalic.ttf
![image](https://github.com/jpt/barlow/assets/12183886/368e3fc9-e391-45bd-9d89-44c9fa985822)

On the other hand, the Barlow Condensed or Barlow font looks correct.
**Correct display**
BarlowCondensed-ThinItalic.ttf
![image](https://github.com/jpt/barlow/assets/12183886/16302e21-5423-43a8-8cff-be4fe808d391)

Barlow-Thin.ttf
![image](https://github.com/jpt/barlow/assets/12183886/bf402624-5ebe-481b-8805-3cec06cdd30d)

**Comment by jpt** [comment]
hi @xcolomer - odd, which version of the font is that? can you test this one and let me know if it is still a problem? thank you for the report
https://github.com/jpt/barlow/archive/refs/heads/1.5.zip

**Comment by xcolomer** [comment]
Hi Jeremy @jpt,
Yes, the source I tried is 1.5.zip. [https://github.com/jpt/barlow/archive/refs/heads/1.5.zip](https://github.com/jpt/barlow/archive/refs/heads/1.5.zip)
This problem occurs with **BarlowSemiCondensed** (Light, LightItalic, Thin, ThinItalic, ExtraLight, ExtraLightItalic).
It is probably a problem for the entire SemiCondensed family, but due to the thickness of the line, in the Regular, SemiBold, Bold, Black,... variants it is not noticeable.

**Comment by jpt** [comment]
I can reproduce it. Working on a fix now

**Comment by jpt** [comment]
Hi @xcolomer - this should be fixed now as of [e8f0d6a](https://github.com/jpt/barlow/commit/e8f0d6a2e0fbfca21ef914b733d990ed5738bcd9), could you try the new binaries at the same 1.5.zip URL?

**Comment by xcolomer** [comment]
Hi Jeremy @jpt,
I download some of the ttf font from the new binaries.
In Mac BarlowSemiCondensed (Thinitalic / Light) **Correct display**:
<img width="622" alt="image" src="https://github.com/jpt/barlow/assets/12183886/27c8a3ac-e4d7-4a8b-9eff-7a32465c463a">

In Windows BarlowSemiCondensed (Light and all) **Incorrect display**:
In small sizes problem with the letters **p** and **d**
![barlow-semicondensed-4](https://github.com/jpt/barlow/assets/12183886/fb3748d6-dbe0-47e8-bb66-a29e0baf63a0)

**Comment by xcolomer** [comment]
@jpt New issue with numbers **6 8 9**
From the same 1.5.zip URL

**Barlow:** Bold, Bolditalic, SemiBold, SemiBolditalic, ExtraBold, ExtraBoldItalic:
Problem in the hole of numbers **6** and **9**
<img width="1086" alt="image" src="https://github.com/jpt/barlow/assets/12183886/77baad63-1e75-4184-a21f-d21f049bc1e4">
<img width="726" alt="image" src="https://github.com/jpt/barlow/assets/12183886/e2fb0c6c-543b-4157-ad3e-d738ad2e8e3e">

**Barlow:** Condensed-Bold, Condensed-BoldItalic, Condensed-SemiBold, Condensed-SemiBolditalic, Condensed-ExtraBold,
Problem with the hole of number **8**
<img width="408" alt="image" src="https://github.com/jpt/barlow/assets/12183886/070d195e-4657-4194-8a19-8fb4bb15ed86">

**Barlow:** SemiCondensed-Black, ...
Problem with the hole of number **8**
<img width="398" alt="image" src="https://github.com/jpt/barlow/assets/12183886/62fab4ff-d3c0-4a9e-8e35-0b4357d6113f">
<img width="275" alt="image" src="https://github.com/jpt/barlow/assets/12183886/85f1d8ef-062b-4cc7-8e60-160e8c19d0f1">

**Comment by jpt** [comment]
thank you, I thought I had fixed the issue with the numbers but will have another look

based on your latest image I know the issue with p and d and will fix that in the evening

**Comment by jpt** [comment]
I have pushed sources as of [1b7db11](https://github.com/jpt/barlow/commit/1b7db11b628f7f3eea46154da3dfde1329323e2e) and will generate and inspect new binaries tomorrow most likely. sorry my timing is a bit off :)

**Comment by xcolomer** [comment]
Hi @jpt 
Something new?

**Comment by jpt** [comment]
thanks for the reminder - try the latest binaries in the 1.5 branch and let me know what you think, the path orders should be fixed as of [2ef48bb](https://github.com/jpt/barlow/commit/2ef48bbcf01efa48ecc5ce2720d1aaddce0f9fc9)

**Comment by xcolomer** [comment]
Hi @jpt 
From [2ef48bb](https://github.com/jpt/barlow/commit/2ef48bbcf01efa48ecc5ce2720d1aaddce0f9fc9)

Barlow: Bold, Bolditalic, SemiBold, SemiBolditalic, ExtraBold, ExtraBoldItalic:
OK the hole of numbers 6 and 9
<img width="505" alt="image" src="https://github.com/jpt/barlow/assets/12183886/da779829-1e7d-4aeb-8e30-b5627515dfea">

Barlow: Condensed and SemiCondensed
OK the hole of number 8
<img width="227" alt="image" src="https://github.com/jpt/barlow/assets/12183886/ad5bfc7b-fecb-4424-84b0-ba1e73582cb3">

**Comment by xcolomer** [comment]
Hi @jpt

In PC Windows
The problem remains with the letters **d** and **p**. Depending on the thickness of the line, the error is more visible in small sizes.

![Captura de pantalla 2024-05-17 182330](https://github.com/jpt/barlow/assets/12183886/5f880c24-b023-4c40-ab30-e195f6fe0607)
![Captura de pantalla 2024-05-07 110344](https://github.com/jpt/barlow/assets/12183886/ca9f4bdf-b0c4-4ef7-8450-78c334cf7ae7)

**Comment by jpt** [comment]
Interesting, I would guess the hints are the issue, I'll have a look

**Comment by xcolomer** [comment]
Hi @jpt
Something new?

**Comment by jpt** [comment]
@xcolomer thanks for reporting this, those letters were components with transformations that broke the new manual hints.  I have fixed the problem and will push up new binaries in next few days.

**Comment by xcolomer** [comment]
Hello Jeremy @jpt ,
Have you had time to update the font files?

thank you

**Comment by jpt** [comment]
Hi Xavi, not yet, but I will have time soon. Thank you for the reminders, and for your patience

**Comment by jpt** [comment]
hi @xcolomer - let me know if this fixes the problem?
[binaries.zip](https://github.com/user-attachments/files/16568194/binaries.zip)
