### ISSUE TITLE
Problems with Umlauts

### ISSUE THREAD

**Issue by gstangl** [jpt/barlow#96]
I have problems with German umlauts in Google Docs. It looks fine when I export it to PDF. When I print it, it looks all wrong, though. The umlauts are all displaced. 

I attached a screenshot. On the left is the original PDF, on the right is a scan of the printout. 
![PDF vs Scan](https://github.com/jpt/barlow/assets/104761/67a2182d-0398-4a5b-8249-0668d1048331)

**Comment by kenmcd** [comment]
My guess is you are using the TTF fonts.
On my phone at the moment so I cannot check the fonts...but
Some printer drivers cannot handle nested components - and the components (the umlauts here) end up in odd places.
OTF fonts cannot use components so they do not have this issue.
So the work-around is to use the OTF fonts instead.

**Comment by Jolg42** [comment]
I didn't test this yet, but maybe it's worth trying:

@gstangl A colleague reported a similar visual issue, but the rendering is of a webpage in a browser, about the backtick character.
See ![image (9)](https://github.com/jpt/barlow/assets/1328733/3fc1e2da-814d-4e8b-af43-d9d7bc75b89b)
I told them to try using the latest version of the font here https://github.com/jpt/barlow/tree/1.5/fonts

**Comment by jpt** [comment]
https://github.com/jpt/barlow/archive/refs/heads/1.5.zip

I have pushed an update that should fix this, can you try the fonts in archive above?

**Comment by Jolg42** [comment]
The problem I mentioned in my previous comment with the back-ticks is fixed in that new version. Thanks a lot 🙌🏼 💚

**Comment by gstangl** [comment]
We are using Barlow mainly via Google Docs. The issue is still there unfortunately.

**Comment by jpt** [comment]
> We are using Barlow mainly via Google Docs. The issue is still there unfortunately.

I appreciate your frustration. I could merge in 1.5 here, but it is unclear to me if Google would accept it in their own repos as they have a new requirement for non-interactive builds (using fontmake, rather than the Glyphs app) for their font collection, which is reasonable. But, this is dependent on glyphsLib, their tool for such non interactive builds, actually working, which may not be the case for Barlow (some of my simpler fonts have been unsupported by glyphsLib for nearly 4 years). So, I will have a look, and maybe we will get lucky about Barlow making it though the gauntlet swiftly, but it’s also possible I will need to work with Google to get all the features it needs into glyphsLib first. I will give you an update when I find out. I haven’t had much time for volunteer work lately, but I expect to have some time at the end of April if not sooner. At the very least I can get 1.5 into the master branch here soon. Apologies for the delay.

**Comment by gstangl** [comment]
Thanks for your work and thorough answer. Please let me know if there is any update here. 

I am working with version 1.5 locally on my Mac it works fine.
